import factory
from factory import fuzzy
from factory.mongoengine import MongoEngineFactory

from src.hr_management_system.departments.models import Department, Position


class DepartmentFactory(MongoEngineFactory):

    """
    Factory for generating Department model instances.

    This factory creates Department objects with random but realistic values:
      - `code`: A random string with a "DEPT-" prefix.
      - `name`: A fake word generated by Faker.
      - `headcount`: Initialized to 0.
    """

    class Meta:
        model = Department

    code = fuzzy.FuzzyText(
        length=5, prefix="DEPT-", chars="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-"
    )
    name = factory.Faker("word", locale="en_US")
    headcount = 0
